chore: 127 | add profile items with icon molecule
Langara-Spiders/alertme pull request #29
Opened 2024-06-20 01:06 UTC by sim0511

2024-06-20 01:30 UTC, BryanCaldeira requested changes

2024-06-20 01:30 UTC, BryanCaldeira commented on components/molecules/ProfileItemsWithIcon.jsx
> +import React from "react";
Please remove this React import

2024-06-20 01:30 UTC, BryanCaldeira commented on pages/Profile.jsx
>  import React from "react";
Same here

2024-06-20 23:04 UTC, sandeepguggilla99 submitted a review, later dismissed

2024-06-22 05:08 UTC, BryanCaldeira approved these changes

2024-06-22 05:28 UTC, merged